# Generated by Django 3.1.4 on 2021-01-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='startingvalue',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='currentvalue',
        ),
    ]
