# Generated by Django 3.1.4 on 2021-01-03 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_auto_20210103_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
