# Generated by Django 3.1.4 on 2021-01-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_transaction_buyvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buyvalue',
        ),
    ]
