# Generated by Django 3.1.4 on 2021-01-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0010_remove_transaction_buyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyvalue',
            field=models.FloatField(default=0),
        ),
    ]
