# Generated by Django 3.1.4 on 2021-01-14 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0011_transaction_buyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sellvalue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shares_remaining',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
