# Generated by Django 3.1.4 on 2021-05-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0014_auto_20210117_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portolio_return',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
